parameters:
    app.link.generator.class:  AppBundle\Services\Implementation\LinkGeneratorService
    app.url.parser.class:  AppBundle\Services\Implementation\UrlParserService

    app.bad.domain.extension.class: AppBundle\Twig\BadDomainExtension

services:

    # services
    app.link.generator:
        class: '%app.link.generator.class%'
        calls:
            - [setRouter, ["@router"]]

    app.url.parser:
        class: '%app.url.parser.class%'

     #twig

    app.bad.domain.extension:
        class: '%app.bad.domain.extension.class%'
        tags:
            - { name: twig.extension }